
const PRODUCTS = [
  // ── Apparel ───────────────────────────────────────────────────────
  {
    id: "performance-windbreaker",
    name: "Performance Windbreaker",
    price: 199,
    category: "Apparel",
    tag: "Bestseller",
    description: "Wind-resistant running jacket with packable hood.",
    images: [
      "https://day-1.com/cdn/shop/files/Windbreakerfirstslide.jpg?v=1758191552&width=800",
      "https://day-1.com/cdn/shop/files/Windbreakernew5.jpg?v=1758191552&width=800",
      "assests/dummy1.jpg",
      "assests/dummy2.jpg",
    ],
  },
  {
    id: "performance-tshirt",
    name: "Performance T-Shirt",
    price: 54,
    category: "Apparel",
    tag: "",
    description: "Breathable moisture-wicking training tee.",
    images: [
      "https://day-1.com/cdn/shop/files/performance-T-shirt-day-one-18.jpg?v=1748737704&width=800",
      "https://day-1.com/cdn/shop/files/performance-T-shirt-day-one---013.jpg?v=1748785834&width=800",
      "assests/dummy1.jpg",
      "assests/Dummy6.jpg",
    ],
  },
  {
    id: "alpine-shell-jacket",
    name: "Alpine Shell Jacket",
    price: 380,
    category: "Apparel",
    tag: "New",
    description: "3-layer waterproof shell for the harshest alpine conditions.",
    images: [
      "assests/dummy1.jpg",
      "assests/dummy5.jpg",
      "assests/dummy2.jpg",
      "assests/Dummy3.jpg",
    ],
  },
  {
    id: "merino-base-layer",
    name: "Merino Base Layer",
    price: 110,
    category: "Apparel",
    tag: "Bestseller",
    description: "Temperature-regulating merino wool base layer.",
    images: [
      "assests/dummy2.jpg",
      "assests/Dummy3.jpg",
      "assests/dummy4.jpg",
      "assests/dummy5.jpg",
    ],
  },
  {
    id: "endurance-tights",
    name: "Endurance Tights",
    price: 120,
    category: "Apparel",
    tag: "",
    description: "Compression running tights with side pocket.",
    images: [
      "assests/dummy4.jpg",
      "assests/dummy2.jpg",
      "assests/Dummy6.jpg",
      "assests/dummy1.jpg",
    ],
  },
  {
    id: "trail-shorts",
    name: "Trail Shorts",
    price: 85,
    category: "Apparel",
    tag: "",
    description: "Quick-dry shorts with integrated brief liner.",
    images: [
      "assests/Dummy6.jpg",
      "assests/dummy4.jpg",
      "assests/Dummy3.jpg",
      "assests/dummy5.jpg",
    ],
  },

  // ── Accessories ───────────────────────────────────────────────────
  {
    id: "summit-pack-20l",
    name: "Summit Pack 20L",
    price: 180,
    category: "Accessories",
    tag: "New",
    description: "Ultralight running vest for long-distance races.",
    images: [
      "assests/Dummy3.jpg",
      "assests/dummy1.jpg",
      "assests/dummy5.jpg",
      "assests/dummy4.jpg",
    ],
  },
  {
    id: "vision-cap",
    name: "Vision Cap",
    price: 45,
    category: "Accessories",
    tag: "",
    description: "Lightweight running cap with UV protection.",
    images: [
      "assests/dummy5.jpg",
      "assests/Dummy3.jpg",
      "assests/dummy2.jpg",
      "assests/dummy1.jpg",
    ],
  },
  {
    id: "trail-gloves",
    name: "Trail Gloves",
    price: 55,
    category: "Accessories",
    tag: "",
    description: "Touchscreen-compatible running gloves for cold trails.",
    images: [
      "assests/dummy1.jpg",
      "assests/dummy4.jpg",
      "assests/Dummy6.jpg",
      "assests/Dummy3.jpg",
    ],
  },
  {
    id: "hydration-flask-500ml",
    name: "Hydration Flask 500ml",
    price: 35,
    category: "Accessories",
    tag: "Bestseller",
    description: "Soft flask with bite valve for on-the-run hydration.",
    images: [
      "assests/dummy4.jpg",
      "assests/dummy5.jpg",
      "assests/dummy2.jpg",
      "assests/Dummy3.jpg",
    ],
  },
];
